
set(ENABLED_GEMS
    TiagoSimulation
    Atom
    AudioSystem
    AWSCore
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    PhysX5
    PrimitiveAssets
    PrefabBuilder
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    DiffuseProbeGrid
    Compression
    ROS2
)
